//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_MVC_PARTE_I.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumno
    {
        public int Id { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public int Edad { get; set; }
        public string Sexo { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public int CodCiudad { get; set; }
    
        public virtual Ciudad Ciudad { get; set; }
    }
}
