//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tarea_01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedidosItems
    {
        public int Id { get; set; }
        public Nullable<int> ClienteId { get; set; }
        public Nullable<int> PeliculaId { get; set; }
        public Nullable<double> total { get; set; }
    
        public virtual clientes clientes { get; set; }
        public virtual peliculas peliculas { get; set; }
    }
}
