//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tarea_01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class peliculas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public peliculas()
        {
            this.PedidosItems = new HashSet<PedidosItems>();
        }
    
        public int id { get; set; }
        public string titulo { get; set; }
        public Nullable<int> duracion { get; set; }
        public Nullable<System.DateTime> publicacion { get; set; }
        public string pais { get; set; }
        public byte[] imagen { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PedidosItems> PedidosItems { get; set; }
    }
}
